### ISSUE TITLE
Compilation error in 1FundamentalGroup/Quest0 in AgdaPad

### ISSUE THREAD

**Issue by CoreyThuro** [thehottgame/theHoTTGameGuide#16]
When I press C+c+C+l in Quest0.agda the following error is thrown:

/home/guest/TheHoTTGame/1FundamentalGroup/Preambles/P0.agda:12,1-35
Multiple definitions of elim. Previous definition at
/nix/store/1l23mh2zzw94nhap3l0i4m1mcsbf9raw-cubical-0.5/Cubical/Data/Bool/Properties.agda:33,1-5
when scope checking the declaration
  open import Cubical.HITs.S1 public

**Comment by Jlh18** [comment]
I believe Ingo Blechschmit fixed this in the other repo - it should be fixed now. Thanks for pointing it out.
