### ISSUE TITLE
Missing `helix.png`

### ISSUE THREAD

**Issue by russellmcc** [thehottgame/theHoTTGameGuide#4]
seems like `helix.png` isn't present, causing no image to appear after the passage

```
since the picture of this ℤ-bundle looks like
```

**Comment by Jlh18** [comment]
yes @kl-i @Blastzit can one of you make it please? I'll make it look less weird by putting a box saying "WIP" or smth

**Comment by Jlh18** [comment]
its done - thanks to @Blastzit  :-)
